### ISSUE TITLE
Project creation fails - groovy.lang.MissingPropertyException: No such property: io for class: bayesianScanner

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1610]
Followup to https://github.com/fabric8-ui/fabric8-platform/issues/1606

Steps to recreate:
* Login to https://openshift.io
* Create new space
* Create new quickstart project ("Add to Space") - accept all defaults

```
GitHub has been notified of this commit’s build result

groovy.lang.MissingPropertyException: No such property: io for class: bayesianScanner
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at org.kohsuke.groovy.sandbox.impl.Checker$4.call(Checker.java:243)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:52)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:308)
	at org.kohsuke.groovy.sandbox.impl.Checker$4.call(Checker.java:241)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:238)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:28)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
```

Full Jenkins log is attached.

[create_project.log.txt](https://github.com/fabric8-ui/fabric8-platform/files/1108955/create_project.log.txt)

**Comment by ldimaggi** [comment]
This problem was seen repeatedly on June 28 - it is not being seen on June 29 - closing.
