### ISSUE TITLE
Creating a new project results in Bayesian error

### ISSUE THREAD

**Issue by ldimaggi** [fabric8-ui/fabric8-ui#1644]
Steps to recreate:
* Create a new Vert.X project - accept all defaults.

Error written to Jenkins log:

```
[Pipeline] bayesianAnalysis
Running Bayesian stack analysis...
Bayesian API URL is https://recommender.api.openshift.io/api/v1
com.redhat.jenkins.plugins.bayesian.BayesianException: Bayesian error: 401
	at com.redhat.jenkins.plugins.bayesian.Bayesian.submitStackForAnalysis(Bayesian.java:86)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:85)
	at com.redhat.jenkins.plugins.bayesian.BayesianAnalysisStep$Execution.run(BayesianAnalysisStep.java:54)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] error
[Pipeline] echo
Unable to run Bayesian analysis: hudson.AbortException: Bayesian analysis failed com.redhat.jenkins.plugins.bayesian.BayesianStepResponse@1f18f15
```

**Comment by joshuawilson** [comment]
@jyasveer @invincibleJai @arunkumars08 Do you know about this and what is causing it?

**Comment by joshuawilson** [comment]
@ldimaggi are you still seeing this?
@jyasveer @invincibleJai @arunkumars08 did you look into this?

**Comment by invincibleJai** [comment]
@joshuawilson got 401 (unauthorised)  due to auth token expiration through Jenkins , it working fine now @arunkumars08 pls confirm.

**Comment by arunkumars08** [comment]
@joshuawilson Tried creating a new space and triggered a build. Logs are fine, UI report is fine too. 
@ldimaggi Could you try once and check if it is still persisting?
@invincibleJai Thanks for looking into.

**Comment by ldimaggi** [comment]
The problem is no longer being seen - closing.
