### ISSUE TITLE
Cannot navigate away from the update profile page

### ISSUE THREAD

**Issue by dlabrecq** [fabric8-ui/fabric8-ui#1737]
I'm having trouble navigate away from the update profile page. I've clicked the update and cancel buttons. I've also selected "Profile" from the user menu in an attempt to navigate back to the profile page. Selecting "Account home" also does nothing. I can only navigate away by selecting a recent space.

**Comment by joshuawilson** [comment]
I just tried it. I did a hard refresh before I started. If you make no changes then the Cancel button is how you leave. If you update something (besides the update tenant) then the Update button at the bottom activates for me and I can leave. Maybe try an in incognito tab.

**Comment by aslakknutsen** [comment]
I'm seeing the same

This is in the console on entry

```
error:
TypeError: co.handleUnderCharsMaxLimit is not a function at Object.eval [as handleEvent] (ng:///UpdateModule/UpdateComponent.ngfactory.js:1603:24) at Object._ [as handleEvent] (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:42812) at Object.handleEvent (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:50989) at dispatchEvent (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:16557) at https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:29643 at SafeSubscriber.t.object.o [as _next] (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:90249) at SafeSubscriber.__tryOrUnsub (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:196635) at SafeSubscriber.next (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:195922) at Subscriber._next (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:194931) at Subscriber.next (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:194566) at EventEmitter.Subject.next (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:281108) at EventEmitter.emit (https://openshift.io/_assets/lib/vendor.e5832f3571174965bc9b.bundle.js:1:89704) at RemainingCharsCountDirective.emitRemainingCharsEvent (https://openshift.io/_assets/lib/14.fd88266ec0b231b3a197.chunk.js:1:59691) at RemainingCharsCountDirective.checkRemainingChars (https://openshift.io/_assets/lib/14.fd88266ec0b231b3a197.chunk.js:1:59490) at RemainingCharsCountDirective.ngOnInit (https://openshift.io/_assets/lib/14.fd88266ec0b231b3a197.chunk.js:1:59124)
id
:
2
url
:
"/aslak/_update"
```

**Comment by joshuawilson** [comment]
I'm seeing it now too.

**Comment by joshuawilson** [comment]
@dlabrecq can you take this one on?

**Comment by dlabrecq** [comment]
Sure

**Comment by joshuawilson** [comment]
there is work being done on the backend to support this at https://github.com/fabric8-services/fabric8-wit/issues/1506

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8-ui/fabric8-ui/pull/1753

**Comment by aslakknutsen** [comment]
@joshuawilson It feels like that comment is a bit missplaced.. :)

**Comment by joshuawilson** [comment]
@aslakknutsen you are right, I was moving too fast and put it on the wrong issue. I deleted my comment. Thanks.
